# Generated by Django 5.1.6 on 2026-01-25 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('professionals', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_telefone', models.CharField(max_length=20)),
                ('codigo_autenticacao', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servico')),
            ],
            options={
                'ordering': ['data_hora_inicio'],
                'unique_together': {('profissional', 'data_hora_inicio')},
            },
        ),
    ]
