# Generated by Django 5.1.6 on 2026-01-25 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(help_text='Identificador único para a URL (ex: barbearia-do-ze)', unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('telefone', models.CharField(help_text='Formato: (24) 9 9216-4962', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('cor_tema', models.CharField(default='#333333', help_text='Cor principal do agendamento (Hex)', max_length=7)),
                ('horarios_padrao', models.JSONField(blank=True, default=dict)),
                ('dono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('abertura', models.TimeField()),
                ('fechamento', models.TimeField()),
                ('fechado', models.BooleanField(default=False, help_text='Se marcado, a loja não abre neste dia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
