# Generated by Django 5.1.6 on 2026-01-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_bairro_empresa_cep_empresa_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='complemento',
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_agendamento_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Janela de Agendamento (dias)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cor_tema',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
