# Generated by Django 5.1.6 on 2026-01-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_empresa_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='diferenciais',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
