# Generated by Django 5.1.6 on 2026-01-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_diferenciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='msg_cancelamento',
            field=models.TextField(default='Olá {cliente}, infelizmente o seu agendamento na {empresa} para o dia {data} às {hora} foi cancelado.'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='msg_confirmacao',
            field=models.TextField(default='Olá {cliente}, seu horário na {empresa} foi confirmado: {data} às {hora}. Profissional: {profissional}.'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='twilio_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='twilio_whatsapp_origem',
            field=models.CharField(blank=True, help_text='Ex: whatsapp:+14155238886', max_length=30, null=True),
        ),
    ]
