# Generated by Django 5.1.6 on 2026-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresa_msg_cancelamento_empresa_msg_confirmacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='template_tema',
            field=models.CharField(choices=[('padrao', 'Padrão (Azul/Clean)'), ('feminino', 'Feminino (Bordô/Pastel)')], default='padrao', max_length=20),
        ),
    ]
