# Generated by Django 5.1.6 on 2026-01-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='icones_categorias/'),
        ),
        migrations.AddField(
            model_name='servico',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='icones_servicos/'),
        ),
    ]
